version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: always
    depends_on:
      - database
    networks:
      - default
    ports:
      - "50051:50051"
volumes:
  data: