version: "3.7"
services:
  grafana:
    image: grafana/grafana:8.0.3
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:v2.28.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter:v1.1.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

  hotrod:
      image: jaegertracing/example-hotrod:latest
      # To run the latest trunk build, find the tag at Docker Hub and use the line below
      # https://hub.docker.com/r/jaegertracing/example-hotrod-snapshot/tags
      #image: jaegertracing/example-hotrod-snapshot:0ab8f2fcb12ff0d10830c1ee3bb52b745522db6c
      ports:
        - "8081:8080"
      command: [ "all" ]
      environment:
        - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      depends_on:
        - jaeger
