global:
  scrape_interval: 5s
  external_labels:
    monitor: 'monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'rest'
    static_configs:
      - targets: ['app:9091']
